### ISSUE TITLE
"Finishing your pdp #13" requires deprecated props

### ISSUE THREAD

**Issue by jpesce** [vtex-trainings/store-framework#6]
Issue #13 requires us to "show the name by SKU variation":
![Screen Shot 2020-07-23 at 20 02 30](https://user-images.githubusercontent.com/1228352/88346752-7642f000-cd1f-11ea-980b-1c5a3a3896ef.png)

It only accepts as a valid answer if the `showValueNameForImageVariation` props is used, but it's currently deprecated:
![Screen Shot 2020-07-23 at 20 03 14](https://user-images.githubusercontent.com/1228352/88346796-91adfb00-cd1f-11ea-9829-84dd87015427.png)

**Comment by fabianaferreira** [comment]
Hi! I actually changed the text of this step to be aligned with what we ask and to avoid this problem of using a deprecated prop. You can check it [here](https://github.com/vtex-apps/store-framework-course/pull/10/files#diff-a91987e603d1112bb910453629eba9cbR66).

Our test is updated to accept `image` as the value for `showValueForVariation`. I just launched a new version of the course fixing this and other problems that we had, in this [pull request](https://github.com/vtex-apps/store-framework-course/pull/10). 

Please, if you find any other problem, feel free to go to this [repo](https://github.com/vtex-apps/store-framework-course), which is where we commit our changes and help us evolving our course. Thanks!
